//@ui5-bundle keepcool/sensormanager/Component-preload.js
sap.ui.require.preload({
	"keepcool/sensormanager/Component.js":function(){
"use strict";sap.ui.define(["sap/ui/core/UIComponent","./model/models"],function(e,t){"use strict";var i=t["createDeviceModel"];var n=e.extend("keepcool.sensormanager.Component",{metadata:{manifest:"json"},init:function t(){e.prototype.init.call(this);this.getRouter().initialize();this.setModel(i(),"device")}});return n});
},
	"keepcool/sensormanager/controller/App.controller.js":function(){
"use strict";sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";var n=e.extend("keepcool.sensormanager.controller.App",{onInit:function e(){}});return n});
},
	"keepcool/sensormanager/controller/SensorStatus.controller.js":function(){
"use strict";sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";var t=e.extend("keepcool.sensormanager.controller.SensorStatus",{onInit:function e(){var t;(t=this.getOwnerComponent().getRouter().getRoute("RouteSensorStatus"))===null||t===void 0||t.attachMatched(this.onRouteMatched,this)},onRouteMatched:function e(t){var n;(n=this.getView())===null||n===void 0||n.bindElement({path:"/sensors/"+t.getParameter("arguments").index,model:"sensorModel"})},navToSensors:function e(){this.getOwnerComponent().getRouter().navTo("RouteSensors")}});return t});
},
	"keepcool/sensormanager/controller/Sensors.controller.js":function(){
"use strict";sap.ui.define(["sap/m/MessageToast","sap/ui/core/mvc/Controller","sap/ui/model/Filter","sap/ui/model/FilterOperator","../format/util"],function(e,t,o,s,n){"use strict";var r=n["Threshold"];var i=t.extend("keepcool.sensormanager.controller.Sensors",{constructor:function e(){t.prototype.constructor.apply(this,arguments);this.statusFilters=[]},onInit:function t(){var o=this.getOwnerComponent();this.getSensorModel().dataLoaded().then(function(){var t=o===null||o===void 0?void 0:o.getModel("i18n");var s=t.getResourceBundle();e.show(s.getText("msgSensorDataLoaded"),{closeOnBrowserNavigation:false})}.bind(this))["catch"](function(t){e.show(t.message,{closeOnBrowserNavigation:false})})},getSensorModel:function e(){var t=this.getOwnerComponent();var o=t===null||t===void 0?void 0:t.getModel("sensorModel");return o},onFilterSelect:function e(t){var n;var i=(n=this.getView())===null||n===void 0||(n=n.byId("sensorsList"))===null||n===void 0?void 0:n.getBinding("items");var a=t.getParameter("key");if(a==="Cold"){this.statusFilters=[new o("temperature",s.LT,r.Warm,false)]}else if(a==="Warm"){this.statusFilters=[new o("temperature",s.BT,r.Warm,r.Hot)]}else if(a==="Hot"){this.statusFilters=[new o("temperature",s.GT,r.Hot,false)]}else{this.statusFilters=[]}i.filter(this.statusFilters)},onCustomerInfoPress:function t(){var o;(o=this.dialog)!==null&&o!==void 0?o:this.dialog=this.loadFragment({name:"keepcool.sensormanager.view.CustomerDialog"});this.dialog.then(function(e){return e.open()})["catch"](function(t){return e.show(t.message)})},onCustomerInfoClose:function t(){this.dialog.then(function(e){e.close()})["catch"](function(t){e.show(t.message)})},navToSensorStatus:function e(t){var o;var s=(o=t.getSource().getBindingContext("sensorModel"))===null||o===void 0?void 0:o.getProperty("index");this.getOwnerComponent().getRouter().navTo("RouteSensorStatus",{index:s})}});return i});
},
	"keepcool/sensormanager/format/util.js":function(){
"use strict";sap.ui.define(["sap/m/library","sap/ui/core/library"],function(r,e){"use strict";var t=r["ValueColor"];var o=e["IconColor"];var a=function(r){r[r["Warm"]=4]="Warm";r[r["Hot"]=5]="Hot";return r}(a||{});function u(r){if(r<a.Warm){return"#0984e3"}else if(r>=a.Warm&&r<a.Hot){return o.Critical}else{return o.Negative}}function n(r,e){if(e==="°F"){r=r*1.8+32}return Math.round(r*10)/10}function i(r){if(r<a.Warm){return t.Neutral}else if(r>=a.Warm&&r<a.Hot){return t.Critical}else{return t.Error}}var l={__esModule:true};l.Threshold=a;l.formatIconColor=u;l.formatTemperature=n;l.formatValueColor=i;return l});
},
	"keepcool/sensormanager/i18n/i18n.properties":'title=Keep Cool Inc. Sensor Manager\nappTitle=Sensor Manager\nappDescription=The sensor manager\nnoSensorDataText=No Sensor Data\nmsgSensorDataLoaded=All sensors online!\nmsgFilterAll=All\nmsgFilterCold=Cold\nmsgFilterWarm=Warm\nmsgFilterHot=Too Hot\ntoolTipShowCustomers=Show Customers\ntitleCustomerDialog=Customers\ntitleSensorStatus=Sensor Status\ncardTitle=Customer\ntemperatureUnit=\\u00b0C',
	"keepcool/sensormanager/i18n/i18n_en.properties":'title=Keep Cool Inc. Sensor Manager\nappTitle=Sensor Manager\nappDescription=The sensor\nnoSensorDataText=No Sensor Data\nmsgSensorDataLoaded=All sensors online!\nmsgFilterAll=All\nmsgFilterCold=Cold\nmsgFilterWarm=Warm\nmsgFilterHot=Too Hot\ntoolTipShowCustomers=Show Customers\ntitleCustomerDialog=Customers\ntitleSensorStatus=Sensor Status\ncardTitle=Customer\ntemperatureUnit=\\u00b0F',
	"keepcool/sensormanager/i18n/i18n_hi.properties":'title=\\u0915\\u0942\\u0932 \\u0930\\u0916\\u0947\\u0902 \\u0907\\u0902\\u0915\\u0964 \\u0938\\u0947\\u0902\\u0938\\u0930 \\u092e\\u0948\\u0928\\u0947\\u091c\\u0930\nappTitle=\\u0938\\u0947\\u0902\\u0938\\u0930 \\u092e\\u0948\\u0928\\u0947\\u091c\\u0930\nappDescription=\\u0938\\u0947\\u0902\\u0938\\u0930 \\u092e\\u0948\\u0928\\u0947\\u091c\\u0930\nnoSensorDataText=\\u0915\\u094b\\u0908 \\u0938\\u0947\\u0902\\u0938\\u0930 \\u0921\\u0947\\u091f\\u093e \\u0928\\u0939\\u0940\\u0902\nmsgSensorDataLoaded=\\u0938\\u092d\\u0940 \\u0938\\u0947\\u0902\\u0938\\u0930 \\u0911\\u0928\\u0932\\u093e\\u0907\\u0928 \\u0939\\u0948\\u0902!\nmsgFilterAll=\\u0938\\u092d\\u0940\nmsgFilterCold=\\u0920\\u0902\\u0921\\u093e\nmsgFilterWarm=\\u0917\\u0930\\u094d\\u092e\nmsgFilterHot=\\u092c\\u0939\\u0941\\u0924 \\u0917\\u0930\\u094d\\u092e\ntoolTipShowCustomers=\\u0917\\u094d\\u0930\\u093e\\u0939\\u0915 \\u0926\\u093f\\u0916\\u093e\\u090f\\u0902\ntitleCustomerDialog=\\u0917\\u094d\\u0930\\u093e\\u0939\\u0915\ntitleSensorStatus=\\u0938\\u0947\\u0902\\u0938\\u0930 \\u0938\\u094d\\u0925\\u093f\\u0924\\u093f\ncardTitle=\\u0917\\u094d\\u0930\\u093e\\u0939\\u0915\ntemperatureUnit=\\u00b0C',
	"keepcool/sensormanager/manifest.json":'{"_version":"1.58.0","sap.app":{"id":"keepcool.sensormanager","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.11.2","toolsId":"765d5192-1e9c-4106-9e86-c894ba112fe6"},"dataSources":{"sensorSource":{"type":"JSON","uri":"./localData/sensors.json"}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"dependencies":{"minUI5Version":"1.119.2","libs":{"sap.m":{},"sap.ui.core":{},"sap.f":{},"sap.suite.ui.generic.template":{},"sap.ui.comp":{},"sap.ui.generic.app":{},"sap.ui.table":{},"sap.ushell":{},"sap.ui.layout":{},"sap.suite.ui.microchart":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"keepcool.sensormanager.i18n.i18n","supportedLocales":["hi","en"],"fallbackLocale":"en"}},"sensorModel":{"type":"sap.ui.model.json.JSONModel","dataSource":"sensorSource"}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"keepcool.sensormanager.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteSensors","pattern":":?query:","target":["TargetSensors"]},{"name":"RouteSensorStatus","pattern":"sensor/{index}","target":["TargetSensorStatus"]}],"targets":{"TargetSensors":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"Sensors","viewName":"Sensors","viewLevel":1},"TargetSensorStatus":{"viewId":"sensorStatus","viewName":"SensorStatus","viewLevel":2}}},"rootView":{"viewName":"keepcool.sensormanager.view.App","type":"XML","async":true,"id":"App"}},"sap.cloud":{"public":true,"service":"keepcoolsensormanager"}}',
	"keepcool/sensormanager/model/models.js":function(){
"use strict";sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,i){"use strict";function n(){var n=new e(i);n.setDefaultBindingMode("OneWay");return n}var t={__esModule:true};t.createDeviceModel=n;return t});
},
	"keepcool/sensormanager/view/App.view.xml":'<mvc:View controllerName="keepcool.sensormanager.controller.App"\n    xmlns:html="http://www.w3.org/1999/xhtml"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"><App id="app"></App></mvc:View>\n',
	"keepcool/sensormanager/view/CustomerDialog.fragment.xml":'<core:FragmentDefinition\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"><Dialog\n        title="{i18n>titleCustomerDialog}"\n        icon="sap-icon://message-information"\n        contentHeight="50%"\n        resizable="true"\n        draggable="true"><content><List\n                items="{\n                    path: \'sensorModel>/customers\',\n                    sorter: {path:\'name\'}\n                }"><StandardListItem title="{sensorModel>name}"/></List></content><buttons><Button text="Close" press=".onCustomerInfoClose"/></buttons></Dialog></core:FragmentDefinition>',
	"keepcool/sensormanager/view/SensorStatus.view.xml":'<mvc:View\n    controllerName="keepcool.sensormanager.controller.SensorStatus"\n    displayBlock="true"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"\n    xmlns:f="sap.f"\n    xmlns:card="sap.f.cards"\n    xmlns:core="sap.ui.core"\n    core:require="{\n        util: \'keepcool/sensormanager/format/util\'\n    }"\n    xmlns:mc="sap.suite.ui.microchart"><Page\n        id="SensorStatusPage"\n        title="{i18n>titleSensorStatus}"\n        showNavButton="true"\n        navButtonPress=".navToSensors"><content><f:Card width="200px" class="sapUiSmallMargin"><f:header><card:NumericHeader title="{i18n>cardTitle} {sensorModel>customer}" subtitle="{sensorModel>location}"\n                        number="{parts: [\'sensorModel>temperature\', \'i18n>temperatureUnit\'], formatter:\'util.formatTemperature\'}"\n                        scale="{i18n>temperatureUnit}" state="{path: \'sensorModel>temperature\', formatter: \'util.formatValueColor\'}" /></f:header><f:content><mc:LineMicroChart\n                        id="lineMicroChart"\n                        class="sapUiSmallMarginBeginEnd sapUiSmallMarginBottom"\n                        leftBottomLabel="15 AM"\n                        rightBottomLabel="15 PM"\n                        threshold="{=util.formatTemperature(util.Threshold.Hot, ${i18n>temperatureUnit})}"\n                        thresholdDisplayValue="{=util.formatTemperature(util.Threshold.Hot, ${i18n>temperatureUnit})} {i18n>temperatureUnit}"\n                        showThresholdValue="true"\n                        size="Auto"\n                        points="{sensorModel>temperatureLog}"><mc:LineMicroChartEmphasizedPoint\n                            x="{sensorModel>time}"\n                            y="{parts: [\'sensorModel>temperature\', \'i18n>temperatureUnit\'], formatter:\'util.formatTemperature\'}"\n                            color="{path: \'sensorModel>temperature\', formatter:\'util.formatValueColor\'}"\n                            show="{=${sensorModel>temperature}>util.Threshold.Warm}"/></mc:LineMicroChart></f:content></f:Card></content></Page></mvc:View>',
	"keepcool/sensormanager/view/Sensors.view.xml":'<mvc:View\n    controllerName="keepcool.sensormanager.controller.Sensors"\n    xmlns:core="sap.ui.core"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"\n    xmlns:f="sap.f"\n    xmlns:grid="sap.ui.layout.cssgrid"\n    core:require="{\n        util: \'keepcool/sensormanager/format/util\'\n    }"\n    displayBlock="true"><Page id="page" title="{i18n>title}"><headerContent><Button icon="sap-icon://information" press=".onCustomerInfoPress" tooltip="{i18n>toolTipShowCustomers}"/></headerContent><content><IconTabBar id="iconTabBar" select=".onFilterSelect" class="sapUiResponsiveContentPadding"><items><IconTabFilter showAll="true" text="{i18n>msgFilterAll}" key="All"/><IconTabSeparator/><IconTabFilter icon="sap-icon://fridge" iconColor="Default" text="{i18n>msgFilterCold}" key="Cold"/><IconTabFilter icon="sap-icon://blur" iconColor="Critical" text="{i18n>msgFilterWarm}" key="Warm"/><IconTabFilter icon="sap-icon://warning" iconColor="Negative" text="{i18n>msgFilterHot}" key="Hot"/></items><content><f:GridList\n                        id="sensorsList"\n                        items="{path: \'sensorModel>/sensors\', sorter: {path:\'customer\', group:true, descending: false}}"\n                        noDataText="No sensors"><f:items><f:GridListItem type="Active" press=".navToSensorStatus"><HBox justifyContent="SpaceBetween"\n                                    class="sapUiSmallMargin"><VBox><Title\n                                            text="{sensorModel>location}"\n                                            wrapping="true"/><ObjectNumber\n                                            number="{parts: [\'sensorModel>temperature\', \'i18n>temperatureUnit\'], formatter:\'util.formatTemperature\'}"\n                                            unit="{i18n>temperatureUnit}"/></VBox><core:Icon\n                                        src="sap-icon://temperature"\n                                        size="2.5rem"\n                                        color="{path: \'sensorModel>temperature\', formatter:\'util.formatIconColor\'}"/></HBox></f:GridListItem></f:items><f:noData><IllustratedMessage enableVerticalResponsiveness="true" illustrationType="sapIllus-EmptyList"/></f:noData></f:GridList></content></IconTabBar></content></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
