//@ui5-bundle keepcool/sensormanager/Component-preload.js
sap.ui.require.preload({
	"keepcool/sensormanager/Component.js":function(){
"use strict";sap.ui.define(["sap/ui/core/UIComponent","./model/models"],function(e,t){"use strict";var i=t["createDeviceModel"];var n=e.extend("keepcool.sensormanager.Component",{metadata:{manifest:"json"},init:function t(){e.prototype.init.call(this);this.getRouter().initialize();this.setModel(i(),"device")}});return n});
},
	"keepcool/sensormanager/controller/App.controller.js":function(){
"use strict";sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";var n=e.extend("keepcool.sensormanager.controller.App",{onInit:function e(){}});return n});
},
	"keepcool/sensormanager/controller/Sensors.controller.js":function(){
"use strict";sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";var n=e.extend("keepcool.sensormanager.controller.Sensors",{onInit:function e(){}});return n});
},
	"keepcool/sensormanager/i18n/i18n.properties":'title=Keep Cool Inc. Sensor Manager\nappTitle=Sensor Manager\nappDescription=The sensor manager\nnoSensorDataText=No Sensor Data\nmsgSensorDataLoaded=All sensors online!\nmsgFilterAll=All\nmsgFilterCold=Cold\nmsgFilterWarm=Warm\nmsgFilterHot=Too Hot\ntoolTipShowCustomers=Show Customers\ntitleCustomerDialog=Customers\ntitleSensorStatus=Sensor Status\ncardTitle=Customer\ntemperatureUnit=\\u00b0C',
	"keepcool/sensormanager/i18n/i18n_en.properties":'title=Keep Cool Inc. Sensor Manager\nappTitle=Sensor Manager\nappDescription=The sensor\nnoSensorDataText=No Sensor Data\nmsgSensorDataLoaded=All sensors online!\nmsgFilterAll=All\nmsgFilterCold=Cold\nmsgFilterWarm=Warm\nmsgFilterHot=Too Hot\ntoolTipShowCustomers=Show Customers\ntitleCustomerDialog=Customers\ntitleSensorStatus=Sensor Status\ncardTitle=Customer\ntemperatureUnit=\\u00b0F',
	"keepcool/sensormanager/i18n/i18n_hi.properties":'title=\\u0915\\u0942\\u0932 \\u0930\\u0916\\u0947\\u0902 \\u0907\\u0902\\u0915\\u0964 \\u0938\\u0947\\u0902\\u0938\\u0930 \\u092e\\u0948\\u0928\\u0947\\u091c\\u0930\nappTitle=\\u0938\\u0947\\u0902\\u0938\\u0930 \\u092e\\u0948\\u0928\\u0947\\u091c\\u0930\nappDescription=\\u0938\\u0947\\u0902\\u0938\\u0930 \\u092e\\u0948\\u0928\\u0947\\u091c\\u0930\nnoSensorDataText=\\u0915\\u094b\\u0908 \\u0938\\u0947\\u0902\\u0938\\u0930 \\u0921\\u0947\\u091f\\u093e \\u0928\\u0939\\u0940\\u0902\nmsgSensorDataLoaded=\\u0938\\u092d\\u0940 \\u0938\\u0947\\u0902\\u0938\\u0930 \\u0911\\u0928\\u0932\\u093e\\u0907\\u0928 \\u0939\\u0948\\u0902!\nmsgFilterAll=\\u0938\\u092d\\u0940\nmsgFilterCold=\\u0920\\u0902\\u0921\\u093e\nmsgFilterWarm=\\u0917\\u0930\\u094d\\u092e\nmsgFilterHot=\\u092c\\u0939\\u0941\\u0924 \\u0917\\u0930\\u094d\\u092e\ntoolTipShowCustomers=\\u0917\\u094d\\u0930\\u093e\\u0939\\u0915 \\u0926\\u093f\\u0916\\u093e\\u090f\\u0902\ntitleCustomerDialog=\\u0917\\u094d\\u0930\\u093e\\u0939\\u0915\ntitleSensorStatus=\\u0938\\u0947\\u0902\\u0938\\u0930 \\u0938\\u094d\\u0925\\u093f\\u0924\\u093f\ncardTitle=\\u0917\\u094d\\u0930\\u093e\\u0939\\u0915\ntemperatureUnit=\\u00b0C',
	"keepcool/sensormanager/manifest.json":'{"_version":"1.58.0","sap.app":{"id":"keepcool.sensormanager","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.11.2","toolsId":"765d5192-1e9c-4106-9e86-c894ba112fe6"},"dataSources":{"sensorSource":{"type":"JSON","uri":"./localData/sensors.json"}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"dependencies":{"minUI5Version":"1.119.2","libs":{"sap.m":{},"sap.ui.core":{},"sap.f":{},"sap.suite.ui.generic.template":{},"sap.ui.comp":{},"sap.ui.generic.app":{},"sap.ui.table":{},"sap.ushell":{},"sap.ui.layout":{},"sap.suite.ui.microchart":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"keepcool.sensormanager.i18n.i18n","supportedLocales":["hi","en"],"fallbackLocale":"en"}},"sensorModel":{"type":"sap.ui.model.json.JSONModel","dataSource":"sensorSource"}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"keepcool.sensormanager.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteSensors","pattern":":?query:","target":["TargetSensors"]}],"targets":{"TargetSensors":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"Sensors","viewName":"Sensors"}}},"rootView":{"viewName":"keepcool.sensormanager.view.App","type":"XML","async":true,"id":"App"}},"sap.cloud":{"public":true,"service":"keepcoolsensormanager"}}',
	"keepcool/sensormanager/model/models.js":function(){
"use strict";sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,i){"use strict";function n(){var n=new e(i);n.setDefaultBindingMode("OneWay");return n}var t={__esModule:true};t.createDeviceModel=n;return t});
},
	"keepcool/sensormanager/view/App.view.xml":'<mvc:View controllerName="keepcool.sensormanager.controller.App"\n    xmlns:html="http://www.w3.org/1999/xhtml"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns="sap.m"><App id="app"></App></mvc:View>\n',
	"keepcool/sensormanager/view/Sensors.view.xml":'<mvc:View\n    controllerName="keepcool.sensormanager.controller.Sensors"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"\n    xmlns:f="sap.f"\n    xmlns:grid="sap.ui.layout.cssgrid"\n    displayBlock="true"><Page id="page" title="{i18n>title}"><content><IconTabBar id="iconTabBar" class="sapUiResponsiveContentPadding"><content><f:GridList\n                        id="sensorsList"\n                        items="{path: \'sensorModel>/sensors\', sorter: {path:\'customer\', group:true, descending: false}}"\n                        noDataText="No sensors"><f:items><f:GridListItem><Title text="{sensorModel>location}"/></f:GridListItem></f:items><f:noData><IllustratedMessage enableVerticalResponsiveness="true" illustrationType="sapIllus-EmptyList"/></f:noData></f:GridList></content></IconTabBar></content></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
